name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Laravel BE
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server generated
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www/test.juggyprojects.com/
            rm -r /var/www/test.juggyprojects.com/Dev-Challenges-ImageUploader-Django-BE
            git clone git@github.com:JUGG097/Dev-Challenges-ImageUploader-Django-BE.git
            cd Dev-Challenges-ImageUploader-Django-BE
            virtualenv myprojectenv
            source myprojectenv/bin/activate
            pip install -r requirements.txt
            pip install gunicorn
            deactivate
            cp /var/www/test.juggyprojects.com/.env_py /var/www/test.juggyprojects.com/Dev-Challenges-ImageUploader-Django-BE/image_upload/.env
            cp /var/www/test.juggyprojects.com/prod_settings.py /var/www/test.juggyprojects.com/Dev-Challenges-ImageUploader-Django-BE/image_upload/settings.py
            systemctl restart imguploaderpy
